sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libvirt-bin
language: java
jdk:
  - oraclejdk8
notifications:
  slack: sddcteam:0kQltMakMELFspYW7JdQuGmL
script: 
  - mvn test cobertura:cobertura -Dcobertura.report.format=xml
  - mvn sonar:sonar
branches:
  only:
    - master
