# blacklist
branches:
  except:
    - docker

# whitelist
branches:
  only:
    - master

sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libvirt-bin
language: java
jdk:
  - oraclejdk8
after_success:
  - mvn clean cobertura:cobertura coveralls:report

